version: '3.4'

services:
  web:
    container_name: docker-node-postgres
    restart: always
    build: .
    links:
      - postgres
    environment:
      # NODE_ENV: development
      DATABASE_URL: "postgres://postgres:Elegeonye123@postgres:5432/postgres"
      # host: postgres
    ports:
      - "8000:5000"
    

  postgres:
    container_name: postgres
    image: "postgres"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345


      