version: '3.4'

services:
  web:
    container_name: docker-node-postgres
    restart: always
    build: .
    links:
      - postgres
    env_file: config.env
    ports:
      - "8000:5000"
    # volumes:
    #   - .:/home/node/app
    #   - node_modules:/home/node/app/node_modules
    

  postgres:
    container_name: postgres
    image: "postgres"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    # volumes:
    #   - dbdata:/var/lib/postgresql/data/

# volumes:
#   dbdata:
#   node_modules:

      